steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$_PROJECT_ID/next-server-repository/next-server-image",
        "--build-arg",
        "_BUILD_CMD=$_BUILD_CMD",
        "--build-arg",
        "_ENV_PATH=$_ENV_PATH",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$_PROJECT_ID/next-server-repository/next-server-image",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "next-server",
        "--image",
        "asia-northeast1-docker.pkg.dev/$_PROJECT_ID/next-server-repository/next-server-image",
        "--region",
        "asia-northeast1",
      ]

images:
  - asia-northeast1-docker.pkg.dev/$_PROJECT_ID/next-server-repository/next-server-image
